service_name: "QuantumPulse"
version: "0.1.0"

# Pulsar Configuration
pulsar:
  service_url: "pulsar://localhost:6650"
  tls_trust_certs_file_path: null
  token: null
  # Topics for the inference pipeline
  topics:
    requests: "persistent://public/default/inference-requests"
    preprocessed: "persistent://public/default/preprocessed-requests"
    # Dynamic routing will go to topics like "routed-model-a-shard-1"
    routed_prefix: "persistent://public/default/routed-"
    results: "persistent://public/default/inference-results"
    feedback: "persistent://public/default/rlhf-feedback"
    analytics: "persistent://public/default/analytics-events"
    model_updates: "persistent://public/default/model-updates"

# API Server Configuration (FastAPI/Uvicorn)
api:
  host: "0.0.0.0"
  port: 8000

# Ignite Configuration for persistent context
ignite:
  addresses:
    - "127.0.0.1:10800"
  cluster_name: "ignite-cluster"
  cache_name: "conversation_context"

# Model Management
models:
  # Configuration for a specific model
  - name: "model-a"
    # Shard topics are derived from the routed_prefix and the model/shard name
    shards:
      - "shard-1"
      - "shard-2"
  - name: "model-b"
    shards:
      - "shard-1"

# Flink Configuration
flink:
  rest_url: "http://localhost:8081"
  # Paths are relative to the project root
  prompt_optimizer_job_path: "QuantumPulse/flink_jobs/prompt_optimizer/prompt_optimizer_job.py"
  dynamic_router_job_path: "QuantumPulse/flink_jobs/dynamic_router/dynamic_router_job.py"

# OpenTelemetry Configuration
otel:
  enabled: true
  endpoint: "http://localhost:4317" # Default OTLP gRPC endpoint for an agent like Jaeger or Tempo 