# .github/workflows/ci.yaml
#
# Reusable CI workflow for Python-based microservices.

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - agentQ
          - AuthQ
          - H2M
          - IntegrationHub
          - KnowledgeGraphQ
          - managerQ
          - VectorStoreQ
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        # Install service-specific dependencies
        if [ -f ${{ matrix.service }}/requirements.txt ]; then pip install -r ${{ matrix.service }}/requirements.txt; fi
        # Install dev dependencies if they exist
        if [ -f ${{ matrix.service }}/requirements-dev.txt ]; then pip install -r ${{ matrix.service }}/requirements-dev.txt; fi

    - name: Lint with ruff
      run: |
        ruff check ./${{ matrix.service }}

    - name: Test with pytest
      run: |
        pytest ./${{ matrix.service }}/tests 